### ISSUE TITLE
日志报错

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/ShitBoyJuJuAddon#3]
[ERROR] cn.hutool.cron.listener.TaskListenerManager: No enum constant net.lawaxi.model.Pocket48MessageType.SHARE_LIVE
W/stderr: java.lang.IllegalArgumentException: No enum constant net.lawaxi.model.Pocket48MessageType.SHARE_LIVE
W/stderr: 	at java.base/java.lang.Enum.valueOf(Enum.java:273)
W/stderr: 	at shitboy-0.1.9-test4.mirai2.jar//net.lawaxi.model.Pocket48MessageType.valueOf(Pocket48MessageType.java:3)
W/stderr: 	at ShitBoyJuJuAddon-0.1.2-test3.mirai2.jar//net.lawaxi.jujuaddon.u.SJAHandler.getMessages(SJAHandler.java:54)
W/stderr: 	at ShitBoyJuJuAddon-0.1.2-test3.mirai2.jar//net.lawaxi.jujuaddon.u.SJASender.run(SJASender.java:43)
W/stderr: 	at ShitBoyJuJuAddon-0.1.2-test3.mirai2.jar//net.lawaxi.jujuaddon.ShitBoyJuJuAddon$1.run(ShitBoyJuJuAddon.java:63)
W/stderr: 	at ShitBoyJuJuAddon-0.1.2-test3.mirai2.jar[private]//cn.hutool.cron.task.RunnableTask.execute(RunnableTask.java:17)
W/stderr: 	at ShitBoyJuJuAddon-0.1.2-test3.mirai2.jar[private]//cn.hutool.cron.task.CronTask.execute(CronTask.java:31)
W/stderr: 	at ShitBoyJuJuAddon-0.1.2-test3.mirai2.jar[private]//cn.hutool.cron.TaskExecutor.run(TaskExecutor.java:52)
W/stderr: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
W/stderr: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
W/stderr: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Lawaxi** [comment]
这应该属于Shitboy的问题，现已修改
