### ISSUE TITLE
0.1.2-test6与shitboy-0.1.11-dev5一起使用日志报错

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/ShitBoyJuJuAddon#6]
W/stderr: Exception in thread "hutool-cron-5" java.lang.IncompatibleClassChangeError: Expecting non-static method 'java.lang.String net.lawaxi.handler.Pocket48Handler.getOwnerOrTeamName(net.lawaxi.model.Pocket48RoomInfo)'
W/stderr:   at ShitBoyJuJuAddon-0.1.2-test6.mirai2.jar//net.lawaxi.jujuaddon.u.SJAHandler.getMessages(SJAHandler.java:31)
W/stderr:   at ShitBoyJuJuAddon-0.1.2-test6.mirai2.jar//net.lawaxi.jujuaddon.u.SJASender.run(SJASender.java:43)
W/stderr:   at ShitBoyJuJuAddon-0.1.2-test6.mirai2.jar//net.lawaxi.jujuaddon.ShitBoyJuJuAddon$1.run(ShitBoyJuJuAddon.java:66)
W/stderr:   at shitboy-0.1.11-dev5.mirai2.jar[shared]//cn.hutool.cron.task.RunnableTask.execute(RunnableTask.java:17)
W/stderr:   at shitboy-0.1.11-dev5.mirai2.jar[shared]//cn.hutool.cron.task.CronTask.execute(CronTask.java:31)
W/stderr:   at shitboy-0.1.11-dev5.mirai2.jar[shared]//cn.hutool.cron.TaskExecutor.run(TaskExecutor.java:52)
W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
W/stderr:   at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Lawaxi** [comment]
刚刚更新0.1.2-test7适配Shitboy-0.1.11-dev1以后版本
